-- Assessment item seed. Text is verbatim from the appendix — do not reword.
-- Order interleaves dimensions and never places a sub-strength's competence
-- and energy items adjacent, so the pattern isn't transparent to respondents.

insert into public.items (id, dimension, sub_strength, item_type, text, sort_order, legacy_tags)
values
  ('thinking.ideation.competence', 'thinking', 'ideation', 'competence',
   'The new ideas I put forward often end up shaping what actually gets done.', 1, null),
  ('influence.mobilizing.competence', 'influence', 'mobilizing', 'competence',
   'When something needs buy-in, I''m usually able to get people genuinely behind it.', 2, array['persuasion','rallying']),
  ('execution.follow_through.competence', 'execution', 'follow_through', 'competence',
   'The things I take on get finished, not just started.', 3, array['follow_through','drive']),
  ('relating.developing_others.competence', 'relating', 'developing_others', 'competence',
   'People seek me out for help getting better at what they do.', 4, array['developing_others','supporting']),
  ('thinking.problem_solving.competence', 'thinking', 'problem_solving', 'competence',
   'The hard problems I take on tend to actually get solved, not just worked on.', 5, null),
  ('influence.communication.competence', 'influence', 'communication', 'competence',
   'When something complex needs explaining to a group, I''m often the one asked to do it.', 6, null),
  ('execution.organizing.competence', 'execution', 'organizing', 'competence',
   'Work I''ve organized tends to run smoothly and keep running after I step back.', 7, array['organizing','structure']),
  ('relating.empathy.competence', 'relating', 'empathy', 'competence',
   'People tend to feel understood by me, sometimes before they''ve fully explained themselves.', 8, null),
  ('thinking.analysis.competence', 'thinking', 'analysis', 'competence',
   'Others often rely on my read of the information to understand what''s really going on.', 9, null),
  ('influence.direction.competence', 'influence', 'direction', 'competence',
   'When a decision was stalling, I''ve been able to step in and get the group to a call.', 10, null),
  ('execution.ownership.competence', 'execution', 'ownership', 'competence',
   'I''m the person people hand something to when it absolutely has to get done.', 11, null),
  ('relating.building_trust.competence', 'relating', 'building_trust', 'competence',
   'The close working relationships I''ve built have lasted and held up under pressure.', 12, null),
  ('thinking.foresight.competence', 'thinking', 'foresight', 'competence',
   'When I''ve called where things were heading, I''ve mostly turned out to be right.', 13, null),
  ('influence.connecting.competence', 'influence', 'connecting', 'competence',
   'New people tend to warm to me quickly.', 14, null),
  ('relating.including.competence', 'relating', 'including', 'competence',
   'People who might otherwise sit at the edges of a group tend to get drawn in when I''m involved.', 15, null),
  ('thinking.judgment.competence', 'thinking', 'judgment', 'competence',
   'Looking back at the calls I''ve made on which ideas to back, they''ve mostly held up.', 16, null),

  ('influence.mobilizing.energy', 'influence', 'mobilizing', 'energy',
   'I come alive when I''m winning people over to something I believe in.', 17, array['persuasion','rallying']),
  ('execution.ownership.energy', 'execution', 'ownership', 'energy',
   'I feel a pull to be the person others can count on to get it done.', 18, null),
  ('relating.empathy.energy', 'relating', 'empathy', 'energy',
   'I''m naturally drawn to paying attention to what the people around me need.', 19, null),
  ('thinking.ideation.energy', 'thinking', 'ideation', 'energy',
   'I get a charge out of dreaming up new ideas, even when no one asked for them.', 20, null),
  ('influence.connecting.energy', 'influence', 'connecting', 'energy',
   'Meeting and drawing in people I don''t yet know is something I actively enjoy.', 21, null),
  ('execution.follow_through.energy', 'execution', 'follow_through', 'energy',
   'I can''t rest easy until something I''ve started is actually done.', 22, array['follow_through','drive']),
  ('relating.building_trust.energy', 'relating', 'building_trust', 'energy',
   'Investing in a close working relationship is something I find genuinely satisfying.', 23, null),
  ('thinking.analysis.energy', 'thinking', 'analysis', 'energy',
   'I enjoy digging into detail and data to work out what''s really happening.', 24, null),
  ('influence.communication.energy', 'influence', 'communication', 'energy',
   'I look for chances to be the one who frames the message or speaks to the room.', 25, null),
  ('execution.organizing.energy', 'execution', 'organizing', 'energy',
   'I enjoy bringing order to something scattered and building the routine that keeps it that way.', 26, array['organizing','structure']),
  ('relating.including.energy', 'relating', 'including', 'energy',
   'I feel a pull to make sure everyone in a group is brought in.', 27, null),
  ('thinking.judgment.energy', 'thinking', 'judgment', 'energy',
   'I like being the one who sizes up whether an idea will hold up.', 28, null),
  ('influence.direction.energy', 'influence', 'direction', 'energy',
   'When a group I''m part of lacks direction, I feel a pull to provide it.', 29, null),
  ('relating.developing_others.energy', 'relating', 'developing_others', 'energy',
   'Helping someone develop is some of the most rewarding work I do.', 30, array['developing_others','supporting']),
  ('thinking.problem_solving.energy', 'thinking', 'problem_solving', 'energy',
   'A knotty problem pulls me in rather than wearing me down.', 31, null),
  ('thinking.foresight.energy', 'thinking', 'foresight', 'energy',
   'Thinking through what''s coming next for the business is work I''d choose to do.', 32, null)
on conflict (id) do update set
  dimension = excluded.dimension,
  sub_strength = excluded.sub_strength,
  item_type = excluded.item_type,
  text = excluded.text,
  sort_order = excluded.sort_order,
  legacy_tags = excluded.legacy_tags;

-- Orientation items (6). text = option A, text_b = option B, direct_side records which side is the direct option.
insert into public.items (id, dimension, sub_strength, item_type, text, text_b, direct_side, sort_order)
values
  ('orientation.1', 'thinking', 'problem_solving', 'orientation',
   'I get more energy from working a hard problem through myself and arriving at a solution.',
   'I get more energy from getting the right people together and working the problem through as a group.',
   'A', 33),
  ('orientation.2', 'thinking', 'judgment', 'orientation',
   'When there''s a call to make on which idea to back, I''d rather form my own view and put it forward.',
   'When there''s a call to make on which idea to back, I''d rather draw out the group''s thinking and help them land it.',
   'A', 34),
  ('orientation.3', 'execution', 'follow_through', 'orientation',
   'I feel most productive when I''m the one doing the work and pushing it to done.',
   'I feel most productive when I''m setting others up to do the work and keeping it moving.',
   'A', 35),
  ('orientation.4', 'execution', 'organizing', 'orientation',
   'I''d rather personally organize the pieces so a project runs the way it should.',
   'I''d rather build the routines that let the team keep a project running without me.',
   'A', 36),
  ('orientation.5', 'influence', 'mobilizing', 'orientation',
   'To move something forward, I''d rather make the case myself and win people over.',
   'To move something forward, I''d rather create the conditions for the group to talk itself into it.',
   'A', 37),
  ('orientation.6', 'influence', 'direction', 'orientation',
   'When a group needs direction, I get energy from being the one who provides it.',
   'When a group needs direction, I get energy from helping the group find its own.',
   'A', 38)
on conflict (id) do update set
  dimension = excluded.dimension,
  sub_strength = excluded.sub_strength,
  item_type = excluded.item_type,
  text = excluded.text,
  text_b = excluded.text_b,
  direct_side = excluded.direct_side,
  sort_order = excluded.sort_order;
